name: 'PR'
on:
  pull_request:
    types:
      - opened
      - synchronize

permissions: write-all

jobs:
  plan:
    name: Plan
    uses: ./.github/workflows/cdktf.yaml
    with:
      mode: plan-only
      stack: demo
      working-dir: .
    secrets: inherit
